{% set name = "unearth" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unearth-{{ version }}.tar.gz
  sha256: 130d0c59159795ae66986c1dcbe5d2ddd1da19841972d8d73510d5204b3817ea

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pdm build -vv
    - {{ PYTHON }} -m pip install dist/unearth-{{ version }}-py3-none-any.whl -vv
  entry_points:
    - unearth = unearth.__main__:cli
  number: 0

requirements:
  host:
    - pip <22.2
    - python >=3.7
    - pdm
    - pdm-pep517
    - setuptools
  run:
    - cached-property >=1.5.2
    - packaging >=20
    - python >=3.7
    - requests >=2.25

test:
  imports:
    - unearth
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pip
    - pytest >=6.1
    - pytest-httpserver >=1.0.4
    - flask >=2.1.2
    - requests-wsgi-adapter >=0.4.1
    - trustme >=0.9.0
    - keyring
    - openssl <3.0.0

about:
  home: https://pypi.org/project/unearth/
  summary: A utility to fetch and download python packages
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
