{% set name = "unearth" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unearth-{{ version }}.tar.gz
  sha256: e2341ba7b99e431955a10cd3da0c15ab0d42a5f9cb3f1e3f460df42bc3396dcf

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unearth = unearth.__main__:cli
  number: 0

requirements:
  host:
    - pip <22.2
    - python >=3.7
    - pdm-pep517
    - setuptools
  run:
    - cached-property >=1.5.2
    - packaging >=20
    - python >=3.7
    - requests >=2.25

test:
  imports:
    - unearth
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pip
    - pytest >=6.1
    - pytest-httpserver >=1.0.4
    - flask >=2.1.2
    - requests-wsgi-adapter >=0.4.1
    - trustme >=0.9.0
    - keyring
    - openssl <3.0.0

about:
  home: https://pypi.org/project/unearth/
  summary: A utility to fetch and download python packages
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
